# Generated by Django 4.0.2 on 2023-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_question_quiz_delete_answer_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='imageUrl',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
    ]
