# Generated by Django 4.0.2 on 2023-10-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='imageUrl',
            field=models.URLField(max_length=500),
        ),
    ]
