# Generated by Django 4.0.2 on 2023-10-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_result_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/'),
        ),
    ]
