# Generated by Django 4.0.2 on 2023-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='capestonequiz/media/quiz_images'),
        ),
    ]
