# Generated by Django 4.0.2 on 2023-10-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(null=True, upload_to='quiz/images'),
        ),
    ]
