# Generated by Django 4.0.2 on 2023-10-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_quiz_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.AddField(
            model_name='quiz',
            name='imageUrl',
            field=models.URLField(max_length=800, null=True),
        ),
    ]
