# Generated by Django 4.0.2 on 2023-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_remove_quiz_image_quiz_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='imageUrl',
            field=models.URLField(default='https://example.com/default_image.jpg', max_length=1024),
        ),
    ]
