# Generated by Django 4.0.2 on 2023-10-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_quiz_imageurl_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
